main: com.shanebeestudios.skbee.SkBee
name: SkBee-Continued
version: '@version@'
description: "A fork of SkBee-Continued which is a simple Skript addon to help customize your server to the fullest."
api-version: '1.13'
contributors: [ShaneBee, Equipable]
website: https://github.com/EquipableMC/SkBee-Continued
depend:
    - Skript
loadbefore:
    - SkQuery
commands:
    skbee:
        description: Main SkBee command
        permission: skbee.command
permissions:
    skbee.admin:
        default: op
        description: Permission to receive error messages
    skbee.command:
        default: op
        description: Permission to use SkBee's main command
