blank_issues_enabled: false
contact_links:
  - name: 🦆 skUnity Discord
    url: https://discord.gg/skript
    about: For general help with SkBee-Continued join skUnity's Discord
  - name: 🚰 SpigotMC Resource
    url: https://www.spigotmc.org/resources/skbee-continued.120039/
    about: Read about SkBee-Continued!
